# Generated by Django 4.2.11 on 2024-04-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created',
        ),
    ]
